# Generated by Django 3.0 on 2019-12-19 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='インターバル')),
                ('url', models.URLField(verbose_name='URL')),
                ('xpath', models.CharField(max_length=225, verbose_name='xpath')),
                ('interval', models.CharField(max_length=1, verbose_name='インターバル')),
                ('trigger_number', models.IntegerField(verbose_name='インターバル')),
                ('description', models.TextField(blank=True, null=True, verbose_name='概要')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザ')),
            ],
            options={
                'db_table': 'scrape_target',
            },
        ),
        migrations.CreateModel(
            name='ScrapeResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='インターバル')),
                ('time', models.DateTimeField(verbose_name='最終採取時間')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.ScrapeTarget', verbose_name='ScrapeTarget')),
            ],
            options={
                'db_table': 'scrape_result',
            },
        ),
    ]
