# Generated by Django 3.0 on 2019-12-20 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapetarget',
            name='trigger_number',
            field=models.IntegerField(verbose_name='開始時点'),
        ),
    ]
