# Generated by Django 3.0 on 2019-12-20 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20191220_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapetarget',
            name='name',
            field=models.CharField(max_length=255, verbose_name='フィールド名'),
        ),
    ]
