# Generated by Django 3.0 on 2019-12-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20191220_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraperesult',
            name='value',
            field=models.CharField(max_length=255, verbose_name='採取値'),
        ),
    ]
