# Generated by Django 3.0 on 2019-12-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20191224_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapetarget',
            name='interval',
            field=models.CharField(blank=True, choices=[('h', 'HOUR'), ('d', 'DAY')], default='d', max_length=1, verbose_name='インターバル'),
        ),
        migrations.AlterField(
            model_name='scrapetarget',
            name='trigger_number',
            field=models.IntegerField(blank=True, default=0, verbose_name='開始時点'),
        ),
    ]
