# Generated by Django 3.0 on 2019-12-25 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20191224_0905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapetarget',
            old_name='user',
            new_name='owner',
        ),
    ]
